---
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpanm --quiet --notest --installdeps .
# cpanm --notest --skip-satisfied Pod::Weaver::Section::Support Test::Pod Text::Autoformat Test::TrailingSpace
#  - dzil authordeps         | cpanm --notest --skip-satisfied
#  - dzil listdeps --author  | cpanm --notest --skip-satisfied
  
language: perl
perl:
  - '5.8'
# - '5.10'
# - '5.12'
# - '5.14'
# - '5.16'
# - '5.18'
# - '5.20'
# - '5.22'
# - '5.24'
# - '5.26'
# - '5.28'
#script:
#  - dzil test --all
